# Generated by Django 5.2.5 on 2025-08-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('db_name', models.CharField(max_length=100)),
                ('db_user', models.CharField(max_length=100)),
                ('db_password', models.CharField(max_length=100)),
                ('db_host', models.CharField(default='localhost', max_length=100)),
                ('db_port', models.CharField(default='5432', max_length=10)),
                ('db_type', models.CharField(choices=[('self_hosted', 'Self Hosted'), ('client_hosted', 'Client Hosted')], default='self_hosted', max_length=20)),
            ],
        ),
    ]
