# Generated by Django 5.2.5 on 2025-08-09 06:11

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatabase',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='userdatabase',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='uniq_userdatabase_username_ci'),
        ),
    ]
