# Generated by Django 5.2.5 on 2025-08-11 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('building_id', models.IntegerField()),
                ('floor_id', models.IntegerField()),
                ('unit_id', models.IntegerField()),
                ('vendor_id', models.IntegerField(blank=True, null=True)),
                ('po_id', models.IntegerField(blank=True, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('altitude', models.CharField(blank=True, max_length=50, null=True)),
                ('asset_name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('asset_type', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=50)),
                ('subgroup', models.CharField(max_length=50)),
                ('capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(max_length=50)),
                ('critical', models.BooleanField(default=False)),
                ('asset_reading', models.BooleanField(default=False)),
                ('compliance', models.BooleanField(default=False)),
                ('breakdown', models.BooleanField(default=False)),
                ('in_use', models.BooleanField(default=False)),
                ('maintained_by', models.IntegerField(blank=True, null=True)),
                ('monitored_by', models.IntegerField(blank=True, null=True)),
                ('managed_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('attachment_type', models.CharField(choices=[('invoice', 'Purchase Invoice'), ('insurance', 'Insurance'), ('manuals', 'Manuals'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='asset_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.asset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('measure_type', models.CharField(choices=[('consumption', 'Consumption'), ('nonConsumption', 'Non Consumption')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('unit_type', models.CharField(max_length=50)),
                ('min_value', models.CharField(blank=True, max_length=50, null=True)),
                ('max_value', models.CharField(blank=True, max_length=50, null=True)),
                ('alert_below', models.CharField(blank=True, max_length=50, null=True)),
                ('alert_above', models.CharField(blank=True, max_length=50, null=True)),
                ('multiplier', models.CharField(blank=True, max_length=50, null=True)),
                ('check_previous', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='api.asset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetPurchaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('po_number', models.CharField(max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('end_of_life', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_info', to='api.asset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetWarrantyAMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('warranty_type', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty_start', models.DateField(blank=True, null=True)),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('under_warranty', models.CharField(default='No', max_length=5)),
                ('amc_type', models.CharField(blank=True, max_length=100, null=True)),
                ('amc_start', models.DateField(blank=True, null=True)),
                ('amc_end', models.DateField(blank=True, null=True)),
                ('amc_provider', models.CharField(blank=True, max_length=200, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_amc', to='api.asset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
