# Generated by Django 5.2.5 on 2025-08-19 14:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('building_id', models.IntegerField()),
                ('floor_id', models.IntegerField()),
                ('unit_id', models.IntegerField()),
                ('vendor_id', models.IntegerField(blank=True, null=True)),
                ('po_id', models.IntegerField(blank=True, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('altitude', models.CharField(blank=True, max_length=50, null=True)),
                ('asset_name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(max_length=50)),
                ('critical', models.BooleanField(default=False)),
                ('asset_reading', models.BooleanField(default=False)),
                ('compliance', models.BooleanField(default=False)),
                ('breakdown', models.BooleanField(default=False)),
                ('in_use', models.BooleanField(default=False)),
                ('maintained_by', models.IntegerField(blank=True, null=True)),
                ('monitored_by', models.IntegerField(blank=True, null=True)),
                ('managed_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('attachment_type', models.CharField(choices=[('invoice', 'Purchase Invoice'), ('insurance', 'Insurance'), ('manuals', 'Manuals'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='asset_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.asset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='api.assetcategory'),
        ),
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='api.assetcategory')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='api.assetgroup'),
        ),
        migrations.CreateModel(
            name='AssetMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('measure_type', models.CharField(choices=[('consumption', 'Consumption'), ('nonConsumption', 'Non Consumption')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('unit_type', models.CharField(max_length=50)),
                ('min_value', models.CharField(blank=True, max_length=50, null=True)),
                ('max_value', models.CharField(blank=True, max_length=50, null=True)),
                ('alert_below', models.CharField(blank=True, max_length=50, null=True)),
                ('alert_above', models.CharField(blank=True, max_length=50, null=True)),
                ('multiplier', models.CharField(blank=True, max_length=50, null=True)),
                ('check_previous', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='api.asset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetPurchaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('po_number', models.CharField(max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('end_of_life', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_info', to='api.asset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetSubgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='api.assetgroup')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='api.assetsubgroup'),
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('site_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['site_id', 'name'], name='api_assetty_site_id_642283_idx'), models.Index(fields=['site_id', 'code'], name='api_assetty_site_id_d63da1_idx')],
                'constraints': [models.UniqueConstraint(fields=('site_id', 'name'), name='uniq_type_name_per_site'), models.UniqueConstraint(fields=('site_id', 'code'), name='uniq_type_code_per_site')],
            },
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.assettype'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='api.assettype'),
        ),
        migrations.CreateModel(
            name='AssetWarrantyAMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('warranty_type', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty_start', models.DateField(blank=True, null=True)),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('under_warranty', models.BooleanField(default=False)),
                ('amc_type', models.CharField(blank=True, max_length=100, null=True)),
                ('amc_start', models.DateField(blank=True, null=True)),
                ('amc_end', models.DateField(blank=True, null=True)),
                ('amc_provider', models.CharField(blank=True, max_length=200, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_amc', to='api.asset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='assetgroup',
            index=models.Index(fields=['category', 'name'], name='api_assetgr_categor_026361_idx'),
        ),
        migrations.AddIndex(
            model_name='assetgroup',
            index=models.Index(fields=['category', 'code'], name='api_assetgr_categor_d33132_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetgroup',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='uniq_group_name_per_category'),
        ),
        migrations.AddConstraint(
            model_name='assetgroup',
            constraint=models.UniqueConstraint(fields=('category', 'code'), name='uniq_group_code_per_category'),
        ),
        migrations.AddIndex(
            model_name='assetsubgroup',
            index=models.Index(fields=['group', 'name'], name='api_assetsu_group_i_dfb90e_idx'),
        ),
        migrations.AddIndex(
            model_name='assetsubgroup',
            index=models.Index(fields=['group', 'code'], name='api_assetsu_group_i_0b4413_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetsubgroup',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='uniq_subgroup_name_per_group'),
        ),
        migrations.AddConstraint(
            model_name='assetsubgroup',
            constraint=models.UniqueConstraint(fields=('group', 'code'), name='uniq_subgroup_code_per_group'),
        ),
        migrations.AddIndex(
            model_name='assetcategory',
            index=models.Index(fields=['asset_type', 'name'], name='api_assetca_asset_t_11c898_idx'),
        ),
        migrations.AddIndex(
            model_name='assetcategory',
            index=models.Index(fields=['asset_type', 'code'], name='api_assetca_asset_t_cd9cd8_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.UniqueConstraint(fields=('asset_type', 'name'), name='uniq_category_name_per_type'),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.UniqueConstraint(fields=('asset_type', 'code'), name='uniq_category_code_per_type'),
        ),
    ]
