# Generated by Django 5.2.5 on 2025-08-20 15:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='building_id',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='floor_id',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='unit_id',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('site_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('building_id', models.IntegerField()),
                ('floor_id', models.IntegerField()),
                ('unit_id', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['site_id', 'building_id', 'floor_id', 'unit_id'], name='api_locatio_site_id_4e3513_idx')],
                'constraints': [models.UniqueConstraint(fields=('site_id', 'building_id', 'floor_id', 'unit_id'), name='uniq_location_per_site_building_floor_unit')],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='api.location'),
            preserve_default=False,
        ),
    ]
