# Generated by Django 5.2.5 on 2025-08-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_asset_building_id_remove_asset_floor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetwarrantyamc',
            name='amc_terms',
            field=models.FileField(blank=True, null=True, upload_to='amc_terms/%Y/%m/'),
        ),
    ]
