# Generated by Django 5.2.5 on 2025-08-23 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_assetwarrantyamc_amc_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetwarrantyamc',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_amc', to='api.asset'),
        ),
    ]
