# Generated by Django 5.2.5 on 2025-09-03 05:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_assetwarrantyamc_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMeasureReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('reading_value', models.DecimalField(decimal_places=4, max_digits=14)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='assetmeasure',
            name='alert_above',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='assetmeasure',
            name='alert_below',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='assetmeasure',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='assetmeasure',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='assetmeasure',
            name='multiplier',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddConstraint(
            model_name='assetmeasure',
            constraint=models.UniqueConstraint(fields=('asset', 'name'), name='uq_asset_measure_name'),
        ),
        migrations.AddField(
            model_name='assetmeasurereading',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='api.assetmeasure'),
        ),
        migrations.AddIndex(
            model_name='assetmeasurereading',
            index=models.Index(fields=['measure', 'created_at'], name='api_assetme_measure_755fd6_idx'),
        ),
    ]
